version: "3.9"

services:
  server:
    container_name: code-sync-server
    build:
      context: ./server
      dockerfile: Dockerfile
      target: runner
    env_file:
      - ./server/.env
    networks:
      - Code-Sync
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  client:
    container_name: code-sync-client
    build:
      context: ./client
      dockerfile: Dockerfile
      target: runner
    networks:
      - Code-Sync
    ports:
      - "5173:80" # local:container
    depends_on:
      - server

  mongo:
    image: mongo:6.0
    container_name: code-sync-mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    networks:
      - Code-Sync
    ports:
      - "27017:27017"

networks:
  Code-Sync:
    driver: bridge

volumes:
  mongo_data:
